[build]
  command = "npm ci --include=dev && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PHASE = "phase-production-build"

# Use the Next.js plugin for server-side rendering
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production" 